### ISSUE TITLE
Unable to map an analogue trigger to a button

### ISSUE THREAD

**Issue by mistydemeo** [OpenJVS/OpenJVS#14]
I'm using two controllers which have all-digital buttons, two of which are mapped to analogue inputs. This is pretty common for arcade sticks and all-digital pads since there's only six digital butons on a 360-style controller, but usually eight buttons to map. I tried to use the following mapping for one controller (a Neo Geo digital gamepad with six face buttons and two shoulder buttons, with the shoulder buttons mapped to analogue L and R triggers):

```
CONTROLLER_ANALOGUE_L CONTROLLER_2 BUTTON_4 PLAYER_2
CONTROLLER_ANALOGUE_R CONTROLLER_2 BUTTON_3 PLAYER_2
```

The L and R buttons don't register in the JVS PCB's input test when pressed. Via `evtest`, I can see that they come up as `0` when not pressed and `255` when pressed.

I'm not sure if I'm missing a keyword to handle analogue-to-digital mapping, or if it's just not supported. If it's not supported, I can take a look at the code and see if I can add it!

**Comment by bobbydilley** [comment]
Hey Misty! Unforunately this isn't supported currently, but it's something I'd love OpenJVS to support and has been asked about before!

I would be very greateful if you'd like to take the time to add it.

The mapping code is a little messy, so feel free to ask me if you've got any questions, I'll have a look tomorrow to see if I've got any pointers etc.

**Comment by mistydemeo** [comment]
Finally took a look at this, and realized that because of how the input mapping works, it'll probably need an additional keyword in the mapping file to indicate it's mapping to a switch - like the `REVERSE` or `SENSITIVITY` mappings. Does that make sense to you? If so, does `DIGITAL` as the key make sense?

**Comment by bobbydilley** [comment]
That does make sense, and `DIGITAL` seems like a good choice to me!
